### ISSUE TITLE
Null value to app.ad_id

### ISSUE THREAD

**Issue by iryna-from-meiro** [iryna-from-meiro/meiro_mobile_SDK#10]
Sometimes when a user opens the app, the app.ad_id is `null` to the events (I came across this twice already). But after some time, it has a value:

<img width="730" alt="Знімок екрана 2024-05-10 о 16 16 43" src="https://github.com/iryna-from-meiro/meiro_mobile_SDK/assets/107461189/ca1f4d45-f22f-48fd-bdaf-51fa42d881e7">
<img width="730" alt="Знімок екрана 2024-05-10 о 16 16 59" src="https://github.com/iryna-from-meiro/meiro_mobile_SDK/assets/107461189/01a06656-1a2c-42d6-9c4c-12ba856ff1cc">

**Comment by davidbilik** [comment]
This is the same as with the fcm token, retrieval of the ad_id is asynchronous, we attach it to events once we receive it from the system.

**Comment by adam-from-meiro** [comment]
Hmm...could you simply buffer the events until the id arrives? Because the value of the data with this information missing is close to zero.

**Comment by davidbilik** [comment]
@adam-from-meiro But we don't know if the id will arrive, that's the problem. Also it's not so simple now to just buffer those events, it would require reworking the mechanism. 

And can you clarify why the value of the data is close to zero without the ad_id?

**Comment by ketys-from-meiro** [comment]
@davidbilik @adam-from-meiro personally I don't care about `ad_id` because if it occurs in some of the following events, it will be extracted into attribute value anyway. 

What could be a problem though is missing fcm token in fcm_registration event. Can this happen? If yes, then it will be rejected on the ME validation level as we need the token for system attribute for sending mobile pushes.

**Comment by davidbilik** [comment]
nope, that can't happen 🙂

**Comment by adam-from-meiro** [comment]
Okay, thanks, closing. Heh. @iryna-from-meiro please close.
